project_name: tart

before:
  hooks:
    - .ci/set-version.sh
    - swift build --arch x86_64 -c release --product tart
    - swift build --arch arm64 -c release --product tart
    - gon gon.hcl

builds:
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - arm64
    binary: tart.app/Contents/MacOS/tart
    prebuilt:
      path: .build/arm64-apple-macosx/release/tart
  - builder: prebuilt
    goos:
      - darwin
    goarch:
      - amd64
    binary: tart.app/Contents/MacOS/tart
    prebuilt:
      path: .build/x86_64-apple-macosx/release/tart

archives:
  - name_template: "{{ .ProjectName }}-{{ .Arch }}"
    files:
      - src: Resources/embedded.provisionprofile
        dst: tart.app/Contents
        strip_parent: true
      - LICENSE

release:
  prerelease: auto

brews:
  - name: tart
    tap:
      owner: cirruslabs
      name: homebrew-cli
    caveats: See the GitHub repository for more information
    homepage: https://github.com/cirruslabs/tart
    license: "Fair Source"
    description: Run macOS and Linux VMs on Apple Hardware
    skip_upload: auto
    dependencies:
      - "cirruslabs/cli/softnet"
    install: |
      libexec.install Dir["*"]
      bin.write_exec_script "#{libexec}/tart.app/Contents/MacOS/tart"
    custom_block: |
      depends_on :macos => :ventura
